server:
  port: 8888

spring:
  application:
    name: cloud-order-service
  # 配置分布式链路追踪 地址 以及采集
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1  # 采样率介于 0 - 1 之间，1 则表示全部采集
eureka:
  client:
    #表示是否将自己注册进EurekaService服务注册中心中，默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认true,单节点无所谓，集群情况下必须设置为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka/   #入驻集群地址
  instance:
    instance-id: payment80
    prefer-ip-address: true #访问路径可以显示IP地址