server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  # nacos 配置 (把服务注册到8848下)
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080  # 配置 sentinel dashboard 地址（web页面地址）
        port: 8719  # 默认是8719端口，假如被占用会自动从8719开始依次+1扫描，直到找到未被占用的端口

#消费者将要访问的服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
