server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:  #路由网关配置
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由功能，利用微服务名称进行路由转发
      routes:  #可以配置多个网关
        - id: payment_routh  #payment_route   #路由的ID，没有固定的规则但要求唯一，建议配合服务名称
          #uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-PAYMENT  #使用微服务名称自动匹配路由
          predicates:
            - Path=/payment/get/**      #断言，路径相匹配的进行路由
        - id: payment_routh2  #payment_route2   #路由的ID，没有固定的规则但要求唯一，建议配合服务名称
          #uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-PAYMENT  #使用微服务名称自动匹配路由
          predicates:
            - Path=/payment/lb/**      #断言，路径相匹配的进行路由
            - After=2020-03-31T10:55:25.088+08:00[GMT+08:00]    #在某个时间刻度之后访问才有效果


eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务器提供者provider 注册进eureka服务列表内
    service-url:
      register-with-eyreka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
